### ISSUE TITLE
Household Dashboard -- Main

### ISSUE THREAD

**Issue by denverdevelopments** [choreorganize/choreganize#4]
- [ ] #9 Shows house name, house members
- [ ] #8 Shows index of suggested/unapproved chores with Approve button
- [ ] #7 Shows index of unfinished chores
- [ ] #6 Shows index of finished chores
